name = "booking-api-public"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Secrets to set via: wrangler secret put <KEY>
# GOOGLE_SHEETS_ID
# GOOGLE_CLIENT_EMAIL
# GOOGLE_PRIVATE_KEY
# ADMIN_API_KEY
# CORS_ORIGINS (comma-separated)

[vars]
NODE_ENV = "production"

# Custom domains
routes = [
  { pattern = "api.marcus.uk/*", custom_domain = true }
]

# Development settings
[env.development]
name = "booking-manager-worker-dev"
vars = { NODE_ENV = "development" }

# Rate limiting with Durable Objects (optional, for advanced rate limiting)
# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"

